# Generated by Django 4.0.3 on 2022-03-16 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awward', '0002_alter_project_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
